routes/backend.php
<?php
/**
 * salad
 * Created by: 5-HT.
 * Date: 02.01.2020 17:30
 *
 * ${PARAM_DOC}
 * ${THROWS_DOC}
 */
use Illuminate\Support\Facades\Route;

Route::group(['prefix' => 'projects'], function(){
    Route::post('/restore', 'ProjectController@restore')->name('projects.restore');
    Route::get('trash', 'ProjectController@deleted')->name('projects.trash');

    Route::resource('', 'ProjectController')
        ->except(['show'])->parameters([
            '' => 'project'
        ])->names('projects');
});

Route::get('home', 'HomeController@index')->name('home');

Route::resource('pages', 'PageController')
    ->except(['show', 'create', 'store'])
    ->names('pages');

Route::resource('media', 'MediaController')
    ->except(['show','create','show','edit','update'])
    ->names('media');
Route::get('get_images', 'MediaController@getImages')->name('media.ajax_get_images');


Route::resource('theme/{slug}/option', 'ThemeOptionController')
    ->only(['index', 'update'])
    ->names('theme_option');

routes/frontend.php
<?php
/**
 * salad
 * Created by: 5-HT.
 * Date: 02.01.2020 17:29
 *
 * Маршрутизация для фронта.
 */

use App\Models\Page;
//use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

//Auth::routes();
Route::get('login', 'Auth\LoginController@showLoginForm')->name('login');
Route::post('login', 'Auth\LoginController@login')->name('login');
Route::post('logout', 'Auth\LoginController@logout')->name('logout');

Route::post('send_message', 'PageController@message')->name('send_message');

Route::get('setlocale/{lang}', 'LocaleController@setLocale')->name('setlocale');

# Single Page
Route::get('', 'PageController@home')->name('page.home');
Route::get('{slug}', 'PageController@page')->name('page');



# Archive
Route::get('{post_type}/{slug}', 'PageController@single')->name('single');

routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Illuminate\Support\Facades\Route;

Route::group(['prefix' => App\Http\Middleware\LocaleMiddleware::getLocale()], function(){

    Route::group([
        'namespace' => 'Backend',
        'prefix' => 'admin',
        'middleware' => ['auth'],
        'as' => 'backend.',
    ], function () {
        include_once 'backend.php';
    });


    Route::group([
        'as' => 'frontend.', 'namespace' => 'Frontend',
    ], function () {
        include_once 'frontend.php';
    });
});

app/Http/Controllers/Frontend/BaseController.php
<?php
/**
 * salad
 * Created by: 5-HT.
 * Date: 03.01.2020 11:00
 *
 * Base controller extends by Controller
 * Abstract
 */


namespace App\Http\Controllers\Frontend;


use App\Http\Controllers\Controller;

abstract class BaseController extends Controller
{

}

app/Http/Controllers/Frontend/LocaleController.php
<?php
/**
 * salad
 * Created by: 5-HT.
 * Date: 03.01.2020 10:12
 *
 * Locale controller to setLocale
 */


namespace App\Http\Controllers\Frontend;


use App\Http\Middleware\LocaleMiddleware;
use Illuminate\Http\RedirectResponse;

class LocaleController extends BaseController
{
    private $referer,
        $languages,
        $mainLanguage;

    public function __construct()
    {
        $this->referer = redirect()->back()->getTargetUrl();
        $this->languages = LocaleMiddleware::$languages;
        $this->mainLanguage = LocaleMiddleware::$mainLanguage;
    }


    /**
     * @param $lang
     * @return \Illuminate\Http\RedirectResponse
     */
    public function setLocale($lang): RedirectResponse
    {
        # STEP 1 - Формирование URI
        $back_uri = str_replace([url('/')], '', $this->referer);

        # STEP 2 - Формируем метку на место смены языка
        $segments = array_filter(explode('/', $back_uri, 3));
        $locale = reset($segments); # LOCALE

        if (in_array($locale, $this->languages)){
            $key = array_search($locale, $segments); # Array KEY Integer
            unset($segments[$key]);
            sort($segments); // Для красоты
        }

        # STEP 3 - Формирование нового URL
        $url = implode( array_merge(
                array_filter([
                    url('/'),
                    $lang!=$this->mainLanguage?$lang:null,
                ]),
                $segments
            ), '/');


        return redirect()->to($url);
    }
}

app/Http/Controllers/Frontend/PageController.php
<?php
/**
 * salad
 * Created by: 5-HT.
 * Date: 03.01.2020 10:12
 *
 * Locale controller to setLocale
 */


namespace App\Http\Controllers\Frontend;

use App\Models\Message;
use App\Services\TypeViewPostType\ArchiveViews;
use App\Services\TypeViewPostType\SingleViews;
use \App\Services\TypeViewPostType\PageViews;
use App\Services\TypeViewPostType\TypeView;
use App\Services\PageFields\ServicePageFields;
use App\Models\Page;
use Illuminate\Http\Request;

class PageController extends BaseController
{
    /**
     * @var Page
     */
    private $page;

    /**
     * @var ServicePageFields
     */
    private $service;

    /**
     * PageController constructor.
     */
    public function __construct()
    {
        $this->page = new Page;
        $this->service = new ServicePageFields;
    }

    /**
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function home()
    {
        $page = $this->page
            ->where('isHomePage', true)
            ->firstOrFail();

        /** @var Page $page */
        return $this->page($page);
    }

    /**
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function page(Page $page)
    {
        if ($page->childs->isNotEmpty()) return $this->archive($page);
        $fields = $this->service->getFieldsByPage($page);# Получить поля данной страницы

        return view(TypeView::getView(new PageViews, $page->slug),
            compact('fields')
        );
    }

    /**
     * @param Page $page
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\Http\RedirectResponse|\Illuminate\View\View
     */
    public function archive(Page $page)
    {
        $list = $this->service->getFieldsByCollection($page->childs);
        $fields = $this->service->getFieldsByPage($page);

        return view(TypeView::getView(new ArchiveViews, $page->slug),
            compact('fields', 'list')
        );
    }

    /**
     * @param $post_type
     * @param $page
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function single(Page $post_type, Page $page)
    {
        $fields = $this->service->getFieldsByPage($page);

        return view(TypeView::getView(new SingleViews, $post_type->slug),
            compact('fields', 'page', 'post_type')
        );
    }

    public function message(Request $request)
    {
        $message = new Message;

        $message->name = $request->name;
        $message->phone = $request->phone;
        $message->message = $request->mssg;

        $message->save();

        return response()->json(['status' => '201']);
    }

}

resources/views/frontend/layouts/app.blade.php
@extends('frontend.html')

@section('body')
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>


                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <li class="nav-item">
                            <a class="nav-link" href="{{ route('frontend.login') }}">{{ __('Login') }}</a>
                        </li>
                        <!-- Authentication Links -->
                        @guest
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('frontend.login') }}">{{ __('Login') }}</a>
                            </li>
                            @if (Route::has('frontend.register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('frontend.register') }}">{{ __('Register') }}</a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('frontend.logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
@endsection

resources/views/frontend/layouts/auth.blade.php
<!doctype html>

<html lang="{{ str_replace('_', '-', app()->getLocale()) }}"  style="height:100%">
<head style="height:100%">
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <!-- Styles -->
    <link href="{{ asset('assets/css/bootstrap.min.css') }}" rel="stylesheet">
    <link href="{{ asset('assets/css/gleb.css') }}" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.11.2/css/all.css">
    <title>@yield('title')</title>
    @yield('style')
</head>
<body style="height:100%">

@yield('content')

<script src="{{ asset('assets/js/jquery-3.4.1.min.js') }}"></script>
<script src="{{ asset('assets/js/popper.min.js') }}"></script>
<script src="{{ asset('assets/js/bootstrap.min.js') }}"></script>

@yield('scripts')

</body>
</html>

resources/views/frontend/layouts/pages.blade.php
@extends('frontend.html')

@section('body')
    <!--HEADER start-->
    <header class="header">
        <div class="site-width">
            <div class="container-fluid">
                <div class="row">

                    <a href="{{ route('frontend.page.home') }}" class="logo">salad</a>

                    <div class="burger" id="burger">
                        <span></span>
                        <span></span>
                        <span></span>
                    </div>

                    <div class="header__right">
                        <div class="cross">
                            <span></span>
                            <span></span>
                        </div>
                        <nav class="navigation">
                            <ul class="nav">
                                <li class="nav__item">
                                    <a href="{{ route('frontend.page', 'projects') }}" class="nav__link">{{ __('page.projects') }}</a>
                                </li>
                                <li class="nav__item">
                                    <a href="{{ route('frontend.page', 'about') }}" class="nav__link">{{ __('page.about') }}</a>
                                </li>
                                <li class="nav__item">
                                    <a href="{{ route('frontend.page', 'vacancies') }}" class="nav__link">{{ __('page.vacancies') }}</a>
                                </li>
                                <li class="nav__item">
                                    <a href="{{ route('frontend.page', 'contacts') }}" class="nav__link">{{ __('page.contacts') }}</a>
                                </li>
                            </ul>
                        </nav>

                        <div class="lang__switch">
                            <span class="lang__active">{{ (app()->getLocale()=="uk"?"ua":app()->getLocale()) }}</span>
                            <ul class="lang__dropdown">
                                <li class="lang__item"><a href="{{ route('frontend.setlocale', 'ru') }}" class="lang__link">ru</a></li>
                                <li class="lang__item"><a href="{{ route('frontend.setlocale', 'uk') }}" class="lang__link">ua</a></li>
                                <li class="lang__item"><a href="{{ route('frontend.setlocale', 'en') }}" class="lang__link">en</a></li>
                            </ul>
                        </div>
                        <div class="phone__links">
                            <a href="" class="phone__link">WELCOME@DIGITAL.SALAD</a>
                            <a href="" class="phone__link">Instagram</a>
                            <a href="" class="phone__link">Facebook</a>
                        </div>

                    </div>

                </div>
            </div>
        </div>
    </header>
    <!--HEADER end-->

    @yield('content')

    @include('admin.includes.admin-menu')

@endsection