routes/backend.php
<?php
/**
 * salad
 * Created by: 5-HT.
 * Date: 02.01.2020 17:30
 *
 * ${PARAM_DOC}
 * ${THROWS_DOC}
 */
use Illuminate\Support\Facades\Route;

Route::group(['prefix' => 'projects'], function(){
    Route::post('/restore', 'ProjectController@restore')->name('projects.restore');
    Route::get('trash', 'ProjectController@deleted')->name('projects.trash');

    Route::resource('', 'ProjectController')
        ->except(['show'])->parameters([
            '' => 'project'
        ])->names('projects');
});

Route::get('home', 'HomeController@index')->name('home');

Route::resource('pages', 'PageController')
    ->except(['show', 'create', 'store'])
    ->names('pages');

Route::resource('media', 'MediaController')
    ->except(['show','create','show','edit','update'])
    ->names('media');
Route::get('get_images', 'MediaController@getImages')->name('media.ajax_get_images');


Route::resource('theme/{slug}/option', 'ThemeOptionController')
    ->only(['index', 'update'])
    ->names('theme_option');

routes/frontend.php
<?php
/**
 * salad
 * Created by: 5-HT.
 * Date: 02.01.2020 17:29
 *
 * Маршрутизация для фронта.
 */

use App\Models\Page;
//use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

//Auth::routes();
Route::get('login', 'Auth\LoginController@showLoginForm')->name('login');
Route::post('login', 'Auth\LoginController@login')->name('login');
Route::post('logout', 'Auth\LoginController@logout')->name('logout');

Route::post('send_message', 'PageController@message')->name('send_message');

Route::get('setlocale/{lang}', 'LocaleController@setLocale')->name('setlocale');

# Single Page
Route::get('', 'PageController@home')->name('page.home');
Route::get('{slug}', 'PageController@page')->name('page');



# Archive
Route::get('{post_type}/{slug}', 'PageController@single')->name('single');

routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Illuminate\Support\Facades\Route;

Route::group(['prefix' => App\Http\Middleware\LocaleMiddleware::getLocale()], function(){

    Route::group([
        'namespace' => 'Backend',
        'prefix' => 'admin',
        'middleware' => ['auth'],
        'as' => 'backend.',
    ], function () {
        include_once 'backend.php';
    });


    Route::group([
        'as' => 'frontend.', 'namespace' => 'Frontend',
    ], function () {
        include_once 'frontend.php';
    });
});

app/Http/Controllers/Frontend/BaseController.php
<?php
/**
 * salad
 * Created by: 5-HT.
 * Date: 03.01.2020 11:00
 *
 * Base controller extends by Controller
 * Abstract
 */


namespace App\Http\Controllers\Frontend;


use App\Http\Controllers\Controller;

abstract class BaseController extends Controller
{

}

app/Http/Controllers/Frontend/LocaleController.php
<?php
/**
 * salad
 * Created by: 5-HT.
 * Date: 03.01.2020 10:12
 *
 * Locale controller to setLocale
 */


namespace App\Http\Controllers\Frontend;


use App\Http\Middleware\LocaleMiddleware;
use Illuminate\Http\RedirectResponse;

class LocaleController extends BaseController
{
    private $referer,
        $languages,
        $mainLanguage;

    public function __construct()
    {
        $this->referer = redirect()->back()->getTargetUrl();
        $this->languages = LocaleMiddleware::$languages;
        $this->mainLanguage = LocaleMiddleware::$mainLanguage;
    }


    /**
     * @param $lang
     * @return \Illuminate\Http\RedirectResponse
     */
    public function setLocale($lang): RedirectResponse
    {
        # STEP 1 - Формирование URI
        $back_uri = str_replace([url('/')], '', $this->referer);

        # STEP 2 - Формируем метку на место смены языка
        $segments = array_filter(explode('/', $back_uri, 3));
        $locale = reset($segments); # LOCALE

        if (in_array($locale, $this->languages)){
            $key = array_search($locale, $segments); # Array KEY Integer
            unset($segments[$key]);
            sort($segments); // Для красоты
        }

        # STEP 3 - Формирование нового URL
        $url = implode( array_merge(
                array_filter([
                    url('/'),
                    $lang!=$this->mainLanguage?$lang:null,
                ]),
                $segments
            ), '/');


        return redirect()->to($url);
    }
}

app/Http/Controllers/Frontend/PageController.php
<?php
/**
 * salad
 * Created by: 5-HT.
 * Date: 03.01.2020 10:12
 *
 * Locale controller to setLocale
 */


namespace App\Http\Controllers\Frontend;

use App\Models\Message;
use App\Services\TypeViewPostType\ArchiveViews;
use App\Services\TypeViewPostType\SingleViews;
use \App\Services\TypeViewPostType\PageViews;
use App\Services\TypeViewPostType\TypeView;
use App\Services\PageFields\ServicePageFields;
use App\Models\Page;
use Illuminate\Http\Request;

class PageController extends BaseController
{
    /**
     * @var Page
     */
    private $page;

    /**
     * @var ServicePageFields
     */
    private $service;

    /**
     * PageController constructor.
     */
    public function __construct()
    {
        $this->page = new Page;
        $this->service = new ServicePageFields;
    }

    /**
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function home()
    {
        $page = $this->page
            ->where('isHomePage', true)
            ->firstOrFail();

        /** @var Page $page */
        return $this->page($page);
    }

    /**
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function page(Page $page)
    {
        if ($page->childs->isNotEmpty()) return $this->archive($page);
        $fields = $this->service->getFieldsByPage($page);# Получить поля данной страницы

        return view(TypeView::getView(new PageViews, $page->slug),
            compact('fields')
        );
    }

    /**
     * @param Page $page
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\Http\RedirectResponse|\Illuminate\View\View
     */
    public function archive(Page $page)
    {
        $list = $this->service->getFieldsByCollection($page->childs);
        $fields = $this->service->getFieldsByPage($page);

        return view(TypeView::getView(new ArchiveViews, $page->slug),
            compact('fields', 'list')
        );
    }

    /**
     * @param $post_type
     * @param $page
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function single(Page $post_type, Page $page)
    {
        $fields = $this->service->getFieldsByPage($page);

        return view(TypeView::getView(new SingleViews, $post_type->slug),
            compact('fields', 'page', 'post_type')
        );
    }

    public function message(Request $request)
    {
        $message = new Message;

        $message->name = $request->name;
        $message->phone = $request->phone;
        $message->message = $request->mssg;

        $message->save();

        return response()->json(['status' => '201']);
    }

}

resources/views/frontend/html.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}"  @yield('attributes_to_html')>

<head>
    <meta charset="UTF-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <meta http-equiv="X-UA-Compatible" content="ie=edge"/>

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <!-- Styles -->
{{--    <link href="{{ asset('assets/css/gleb.css') }}" rel="stylesheet">--}}

    @yield('app.css')

    <link rel="shortcut icon" type="image/png" href="{{ asset('/assets/img/png/favicon.ico') }}"/>

    <title>@yield('title')</title>
</head>

<body class="page" @yield('attributes_to_body')>

<div class="preloader">
    <span class="preloader__title">SALAD</span>
</div>

@yield('body')

<script src="{{ asset('assets/js/jquery-3.4.1.slim.min.js') }}"></script>
<script src="{{ asset('assets/js/popper.min.js') }}"></script>
<script src="{{ asset('assets/js/bootstrap.min.js') }}"></script>


<!--MODALS start-->

<div class="pop-up" id="contactModal">
    <div class="pop-up__content">
        <div class="pop-up__cls">
            <span></span>
            <span></span>
        </div>
        <h3 class="pop-up__title">{{ __('page.contact_title') }} <span class="bordered">{{ __('page.contact_subtitle') }}</span></h3>
        <p class="pop-up__desc">{{ __('page.sub__title_contact') }}</p>
        <form action="{{ route('frontend.send_message') }}" method="POST" class="form pop-up__form" id="feedbackForm">
            @csrf
            <div class="form__row">
                <label for="name">{{ __('page.your_name') }}</label>
                <input
                        type="text"
                        name="name"
                        id="name"
                        placeholder="{{ __('page.ivan_ivanov') }}"
                        data-msg-minlength="Имя должно быть больше 4 символов"
                        data-msg-required="Обязательное поле"
                >
            </div>
            <div class="form__row">
                <label for="phone">{{ __('page.phone_number') }}</label>
                <input
                        type="tel"
                        name="phone"
                        id="phone"
                        placeholder="+38 (000) 0000-000"
                        data-msg-pattern="Не корректный формат номера телефона"
                        data-msg-required="Обязательное поле"
                        maxlength="13">
            </div>
            <div class="form__row">
                <button class="btn-add">{{ __('page.insert_message')  }}</button>
                <div class="msg-block">
                    <input type="text" name="mssg" id="mssg" placeholder="{{ __('page.message') }}">
                </div>
            </div>
            <div class="form__row">
                <input type="submit" value="{{ __('page.send') }}">
            </div>
        </form>
    </div>
</div>
<!--MODALS end-->

<!--FOOTER start-->
<footer class="footer">
    <div class="site-width">
        <div class="container-fluid">
            <div class="row footer__row">
                <a href="{{ route('frontend.page.home') }}" class="logo">salad</a>
                <a href="mailto:{{ TO::settings()->get('settings_email') }}" class="footer__link mail">{{ TO::settings()->get('settings_email') }}</a>
                <div class="footer__social">
                    <a href="{{ TO::settings()->get('settings_instagram_link') }}" class="footer__link">Instagram</a>
                    <a href="{{ TO::settings()->get('settings_facebook_link') }}" class="footer__link">Facebook</a>
                </div>
            </div>
        </div>
    </div>
</footer>
<!--FOOTER end-->

<script src="/js/vendor.js"></script>
<script src="/js/app.js"></script>

</body>

</html>