routes/backend.php
<?php
/**
 * salad
 * Created by: 5-HT.
 * Date: 02.01.2020 17:30
 *
 * ${PARAM_DOC}
 * ${THROWS_DOC}
 */
use Illuminate\Support\Facades\Route;

Route::group(['prefix' => 'projects'], function(){
    Route::post('/restore', 'ProjectController@restore')->name('projects.restore');
    Route::get('trash', 'ProjectController@deleted')->name('projects.trash');

    Route::resource('', 'ProjectController')
        ->except(['show'])->parameters([
            '' => 'project'
        ])->names('projects');
});

Route::get('home', 'HomeController@index')->name('home');

Route::resource('pages', 'PageController')
    ->except(['show', 'create', 'store'])
    ->names('pages');

Route::resource('media', 'MediaController')
    ->except(['show','create','show','edit','update'])
    ->names('media');
Route::get('get_images', 'MediaController@getImages')->name('media.ajax_get_images');


Route::resource('theme/{slug}/option', 'ThemeOptionController')
    ->only(['index', 'update'])
    ->names('theme_option');

routes/frontend.php
<?php
/**
 * salad
 * Created by: 5-HT.
 * Date: 02.01.2020 17:29
 *
 * Маршрутизация для фронта.
 */

use App\Models\Page;
//use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

//Auth::routes();
Route::get('login', 'Auth\LoginController@showLoginForm')->name('login');
Route::post('login', 'Auth\LoginController@login')->name('login');
Route::post('logout', 'Auth\LoginController@logout')->name('logout');

Route::post('send_message', 'PageController@message')->name('send_message');

Route::get('setlocale/{lang}', 'LocaleController@setLocale')->name('setlocale');

# Single Page
Route::get('', 'PageController@home')->name('page.home');
Route::get('{slug}', 'PageController@page')->name('page');



# Archive
Route::get('{post_type}/{slug}', 'PageController@single')->name('single');

routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Illuminate\Support\Facades\Route;

Route::group(['prefix' => App\Http\Middleware\LocaleMiddleware::getLocale()], function(){

    Route::group([
        'namespace' => 'Backend',
        'prefix' => 'admin',
        'middleware' => ['auth'],
        'as' => 'backend.',
    ], function () {
        include_once 'backend.php';
    });


    Route::group([
        'as' => 'frontend.', 'namespace' => 'Frontend',
    ], function () {
        include_once 'frontend.php';
    });
});

app/Models/Media.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Media extends Model
{
    protected $table='media',
        $fillable = ['link', 'storage_path', 'size', 'filename', 'type'];
}

app/Http/Controllers/Backend/MediaController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use App\Models\Media;
use Illuminate\Http\Request;

class MediaController extends Controller
{
    /**
     * @var Media
     */
    private $model;

    public function __construct()
    {
        $this->model = new Media;
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $media = $this->model
            ->orderBy('created_at', 'DESC')
            ->paginate(15);

        return view('admin.media.index',
            compact('media')
        );
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $media = $request->media;

        $mm = collect($media)->map(function ($file) {
            $file = $file->store('public');
            $stor_path = explode('/', $file);

            $filename = end($stor_path);
            $storage_path = storage_path('app\\public\\' . $filename);
            $link = asset("storage/$filename");
            $size = 1;//\File::size($storage_path);
            $type = explode('.', $filename);
            $format = end($type);
            $type = collect(config('filesystems.access_formats'))->map(function ($formats, $type) use ($format) {
                if (in_array($format, $formats))
                    return $type;
            })->filter()->first();

            return compact('link', 'storage_path', 'size', 'filename', 'type');
        });

        Media::insert($mm->toArray());

        return redirect()->back()
            ->with('info', "Число файлов: ".$mm->count().". Успешно загружено!");
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $media = $this->model->find($id);

        $path = storage_path('app\\public\\' . $media->filename);
        if (file_exists($path)) {
            $path_del = storage_path('app\\delete\\' . $media->filename);
            rename($path, $path_del);
        }

        $media->delete();

        return redirect()->back()
            ->with('info', 'Файл успешно удален. Для его восстановления обратитесь к разработчику');
    }


    public function getImages()
    {
        //dd(request()->type);
        $media = $this->model->orderBy('created_at', 'DESC')->get()->map(function($image){
            return [
                'id' => $image->id,
                'type' => $image->type,
                'src' => asset('storage/'.$image->filename),
            ];
        })->toArray();

        return response()->json($media);
    }
}

resources/views/admin/media/index.blade.php
@extends('admin.layouts.default')

@section('style')
    <style>
        .body-flat {
            border-radius: 0;
        }

        .toolbar {
            position: absolute;
            bottom: 70%;
        }

        .col-md-4 .box {
            border: 1px solid silver;
            padding: 10px;
            margin: 5px;
            max-height: 200px;
            min-height: 150px;
            background-image: url({{ asset('assets/img//load-gs.gif') }});
            background-position: center;
            text-align: center;
        }

        img, video {
            width: 100%;
            height: auto;
            max-height: 180px;
        }
    </style>
@endsection

@section('content')
    <div class="container">

        @if(session()->has('info'))
            <div class="alert alert-info">
                {!! session('info') !!}
            </div>
        @endif

        <div class="card body-flat">
            <div class="card-body">
                <form action="{{ route('backend.media.store') }}" method="POST" enctype="multipart/form-data"
                      class="d-flex justify-content-between">
                    @csrf
                    <input type="file" name="media[]" multiple>
                    <input class="btn btn-info btn-block" type="submit" value="Загрузить">
                </form>
            </div>
        </div>

        <div class="card body-flat">
            <div class="card-header">
                <div class="row d-flex justify-content-between">
                    <div class="title">MEDIA</div>
                    <div class="total">
                        Всего: {{ $media->total() }} шт.
                    </div>
                </div>
            </div>
            <div class="card-body">
                <div class="row justify-content-center mb-2">
                    {{ $media->links() }}
                </div>
                <div class="row">
                    @foreach($media as $mm)
                        <div class="col-md-4">
                            <div class="box">
                                @if($mm->type == "image")
                                    <img data-src="{{ asset('storage/'.$mm->filename) }}" alt="">
                                @elseif($mm['type'] == "video")
                                    <video data-src="{{$mm['link']}}" autoplay muted></video>
                                @endif
                                <div class="toolbar">
                                    <form action="{{ route('backend.media.destroy', $mm->id) }}" method="POST">
                                        @method('DELETE')
                                        @csrf
                                        <button type="submit" class="btn btn-danger">Удалить</button>
                                    </form>
                                </div>
                            </div>
                        </div>
                    @endforeach
                </div>
                <div class="row justify-content-center">
                    {{ $media->links() }}
                </div>
            </div>
        </div>
    </div>
@endsection

@section('scripts')
    <script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
    <script>
        $(function () {
            var media = $('img, video');
            for (i = 0; i < media.length; i++) {
                $(media[i]).attr('src',
                    $(media[i]).data('src')
                );
                // $(media[i]).parent().css('background-image', "url("+$(media[i]).data('src')+")");
            }

        })
    </script>
@endsection