routes/backend.php
<?php
/**
 * salad
 * Created by: 5-HT.
 * Date: 02.01.2020 17:30
 *
 * ${PARAM_DOC}
 * ${THROWS_DOC}
 */
use Illuminate\Support\Facades\Route;

Route::group(['prefix' => 'projects'], function(){
    Route::post('/restore', 'ProjectController@restore')->name('projects.restore');
    Route::get('trash', 'ProjectController@deleted')->name('projects.trash');

    Route::resource('', 'ProjectController')
        ->except(['show'])->parameters([
            '' => 'project'
        ])->names('projects');
});

Route::get('home', 'HomeController@index')->name('home');

Route::resource('pages', 'PageController')
    ->except(['show', 'create', 'store'])
    ->names('pages');

Route::resource('media', 'MediaController')
    ->except(['show','create','show','edit','update'])
    ->names('media');
Route::get('get_images', 'MediaController@getImages')->name('media.ajax_get_images');


Route::resource('theme/{slug}/option', 'ThemeOptionController')
    ->only(['index', 'update'])
    ->names('theme_option');

routes/frontend.php
<?php
/**
 * salad
 * Created by: 5-HT.
 * Date: 02.01.2020 17:29
 *
 * Маршрутизация для фронта.
 */

use App\Models\Page;
//use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

//Auth::routes();
Route::get('login', 'Auth\LoginController@showLoginForm')->name('login');
Route::post('login', 'Auth\LoginController@login')->name('login');
Route::post('logout', 'Auth\LoginController@logout')->name('logout');

Route::post('send_message', 'PageController@message')->name('send_message');

Route::get('setlocale/{lang}', 'LocaleController@setLocale')->name('setlocale');

# Single Page
Route::get('', 'PageController@home')->name('page.home');
Route::get('{slug}', 'PageController@page')->name('page');



# Archive
Route::get('{post_type}/{slug}', 'PageController@single')->name('single');

routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Illuminate\Support\Facades\Route;

Route::group(['prefix' => App\Http\Middleware\LocaleMiddleware::getLocale()], function(){

    Route::group([
        'namespace' => 'Backend',
        'prefix' => 'admin',
        'middleware' => ['auth'],
        'as' => 'backend.',
    ], function () {
        include_once 'backend.php';
    });


    Route::group([
        'as' => 'frontend.', 'namespace' => 'Frontend',
    ], function () {
        include_once 'frontend.php';
    });
});

resources/views/admin/layouts/default.blade.php
@extends('admin.html')

@section('body')

<div class="container to-navigation">
    <a href="{{ url()->to('/') }}" class="logo" style="background-color: @yield('color-to-logo');">salad</a>
    {{--<ul style="display: inline-flex;justify-content: space-evenly;width: 50%;">
        <li><a href="{{ route('frontend.page', 'home') }}">{{ __('page.home') }}</a></li>
        <li><a href="{{ route('frontend.page', 'about') }}">{{ __('page.about') }}</a></li>
        <li><a href="{{ route('frontend.page', 'vacancies') }}">{{ __('page.vacancies') }}</a></li>
        <li><a href="{{ route('frontend.page', 'contacts') }}">{{ __('page.contacts') }}</a></li>
        <li><a href="{{ route('frontend.page', 'projects') }}">{{ __('page.projects') }}</a></li>
    </ul>--}}
    <ul class="d-inline-flex justify-content-end w-100 lipadding">
        <li>
            <a href="/setlocale/uk">Ukraine</a>
        </li>
        <li>
            <a href="/setlocale/ru">Russian</a>
        </li>
        <li>
            <a href="/setlocale/en">English</a>
        </li>
    </ul>
</div>

<div class="container">
    <div class="row">
        <div class="col-3">
            <div class="card">
                <div class="card-header">Меню</div>

                <div class="card-body">
                    <ul class="gs_li">
                        <li>
                            <a href="{{ route('backend.home') }}">
                                Главная
                            </a>
                        </li>
                        <li>
                            <a href="{{ route('backend.pages.index') }}">
                                Страницы
                            </a>
                        </li>
                        <li>
                            <a href="{{ route('backend.media.index') }}">
                                Мультимедия
                            </a>
                        </li>
                        <li>
                            <a href="{{ route('backend.projects.index') }}">
                                Проекты
                            </a>
                        </li>
                        @foreach(
                        App\Models\Page::where('type', 'theme_option')->get()
                        as $page
                        )
                            <li>
                                <a href="{{ route('backend.theme_option.index', $page->slug) }}">
                                    {{ $page->fields->where('name', 'title')->first()->value }}
                                </a>
                            </li>
                        @endforeach
                    </ul>
                </div>
            </div>

        </div>
        <div class="col-9">
            @yield('content')
        </div>
    </div>
</div>
@endsection